##
## EPITECH PROJECT, 2019
## Makefile lib
## File description:
## Makefile
##

all:	lib

lib:
		@$(MAKE) --no-print-directory -C Ncurses
		@$(MAKE) --no-print-directory -C SFML
		@$(MAKE) --no-print-directory -C SDL

clean:
		@$(MAKE) clean --no-print-directory -C Ncurses
		@$(MAKE) clean --no-print-directory -C SFML
		@$(MAKE) clean --no-print-directory -C SDL

fclean:
		@$(MAKE) fclean --no-print-directory -C Ncurses
		@$(MAKE) fclean --no-print-directory -C SFML
		@$(MAKE) fclean --no-print-directory -C SDL

re:
		@$(MAKE) re --no-print-directory -C Ncurses
		@$(MAKE) re --no-print-directory -C SFML
		@$(MAKE) re --no-print-directory -C SDL

.PHONY: all clean fclean re