##
## EPITECH PROJECT, 2019
## deBruijn
## File description:
## Makefile
##

RM		=	rm -rf

all:	groundhog

groundhog:
		cp groundhog.py groundhog

clean:
		$(RM) groundhog

fclean: clean

re:		fclean all

.PHONY:	all clean fclean re