##
## EPITECH PROJECT, 2019
## Makefile lib
## File description:
## Makefile
##

all:	build

build:
		@$(MAKE) --no-print-directory -C Snake
		@$(MAKE) --no-print-directory -C Pacman

clean:
		@$(MAKE) clean --no-print-directory -C Snake
		@$(MAKE) clean --no-print-directory -C Pacman

fclean:
		@$(MAKE) fclean --no-print-directory -C Snake
		@$(MAKE) fclean --no-print-directory -C Pacman

re:
		@$(MAKE) re --no-print-directory -C Snake
		@$(MAKE) re --no-print-directory -C Pacman

.PHONY: all clean fclean re